services:
  database:
    env_file:
      - .env
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  auth_service:
    env_file:
      - auth_service/.env
    build:
      context: auth_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"


volumes:
  postgres_data: